lib/surface_app_web/router.ex
defmodule SurfaceAppWeb.Router do
  use SurfaceAppWeb, :router

  import SurfaceAppWeb.UserAuth

  import Surface.Catalogue.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SurfaceAppWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SurfaceAppWeb do
    pipe_through :browser

    get "/", PageController, :index
    live "/demo", Demo
    # live "/home", HomeLive
    # live "/trivia/:category", TriviaLive
  end

  # Other scopes may use custom stacks.
  # scope "/api", SurfaceAppWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: SurfaceAppWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  if Mix.env() == :dev do
    scope "/" do
      pipe_through :browser
      surface_catalogue "/catalogue"
    end
  end

  ## Authentication routes

  scope "/", SurfaceAppWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", SurfaceAppWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
    # Should redirect to login page with red flash message
    live "/home", HomeLive
    live "/trivia/:length/:diff/:category", TriviaLive
    live "/trivia/end", GameOverLive
    live "/social", SocialLive
    live "/chat", ChatLive
    live "/games", LightOutBoardLive
  end

  scope "/", SurfaceAppWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/surface_app_web/controllers/user_registration_controller.ex
defmodule SurfaceAppWeb.UserRegistrationController do
  use SurfaceAppWeb, :controller

  alias SurfaceApp.Accounts
  alias SurfaceApp.Accounts.User
  alias SurfaceAppWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        # {:ok, _} = UserStats.add_stats_record(user)
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :edit, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/surface_app_web/views/user_registration_view.ex
defmodule SurfaceAppWeb.UserRegistrationView do
  use SurfaceAppWeb, :view
end

lib/surface_app_web/templates/user_registration/new.html.heex
<div class="relative flex min-h-screen text-gray-800 antialiased flex-col justify-center overflow-hidden bg-slate-800 py-6 sm:py-12 mt-8">
  <div class="relative py-3 sm:w-96 mx-auto text-center">
    <h1 class="text-2xl font-light ">Register for an account</h1>
      <div class="mt-4 bg-white shadow-md rounded-lg text-left">
        <div class="h-2 bg-purple-400 rounded-t-md"></div>
        <div class="px-8 py-6 ">
        <.form let={f} for={@changeset} action={Routes.user_registration_path(@conn, :create)}>
          <%= if @changeset.action do %>
            <div class="alert alert-danger">
              <p>Oops, something went wrong! Please check the errors below.</p>
            </div>
          <% end %>

          <%= label f, :username, class: "block font-semibold" %>
          <%= text_input f, :username, required: true, class: "border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-indigo-500 focus:ring-1 rounded-md" %>
          <%= error_tag f, :username %>

          <%= label f, :email, class: "block font-semibold" %>
          <%= email_input f, :email, required: true, class: "border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-indigo-500 focus:ring-1 rounded-md" %>
          <%= error_tag f, :email %>

          <%= label f, :password, class: "block mt-3 font-semibold" %>
          <%= password_input f, :password, required: true, class: "border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-indigo-500 focus:ring-1 rounded-md" %>
          <%= error_tag f, :password %>

          <div class="flex justify-between items-baseline">
            <%= submit "Register", class: "mt-4 bg-purple-500 text-white py-2 px-6 rounded-md hover:bg-purple-600" %>
          </div>
        </.form>
        <p>
          <%= link "Log in", to: Routes.user_session_path(@conn, :new) %> |
          <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new), class: "text-sm hover:underline" %>
        </p>
      </div>
    </div>
  </div>
</div>